import { useState, useEffect } from "react";
import { useParams } from "react-router-dom";
import { api, ApiError } from "../api/client";
import { money } from "../components/ui";
import { PrintShell } from "../components/PrintShell";

export default function PrintReceipt() {
  const { saleId } = useParams();
  const [sale, setSale] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    (async () => {
      try {
        setSale(await api.get(`/sales/${saleId}`));
      } catch (err) {
        setError(err instanceof ApiError ? err.message : "Could not load this receipt");
      }
    })();
  }, [saleId]);

  if (error) return <div className="p-8 text-sm text-rose-600">{error}</div>;
  if (!sale) return <div className="p-8 text-sm text-slate-400">Loading...</div>;

  const total = (sale.billingItems || []).reduce((s: number, i: any) => s + Number(i.amount), 0);

  return (
    <PrintShell title="Payment Receipt" subtitle={sale.saleNo} backTo="/sales" backLabel="Back to Sales Lookup">
      <div className="grid grid-cols-2 gap-4 mb-6 text-sm">
        <div>
          <p className="text-xs font-medium text-slate-500 mb-1">Customer</p>
          <p className="font-medium">{sale.customerName || "Walk-in"}</p>
          {sale.customerPhone && <p className="text-slate-600">{sale.customerPhone}</p>}
        </div>
        <div>
          <p className="text-xs font-medium text-slate-500 mb-1">Sale</p>
          <p className="text-slate-600">{sale.saleNo}</p>
          <p className="text-slate-600">{new Date(sale.createdAt).toLocaleString()}</p>
        </div>
      </div>

      <p className="text-xs font-semibold text-dhs-800 uppercase tracking-wide mb-2 border-b border-slate-200 pb-1">Items</p>
      <table className="w-full text-sm mb-6">
        <tbody>
          {sale.items.map((li: any) => (
            <tr key={li.id} className="border-b border-slate-100">
              <td className="py-1.5">{li.item.name}</td>
              <td className="py-1.5 text-center">x{li.quantity}</td>
              <td className="py-1.5 text-right">{money(Number(li.unitPrice) * li.quantity)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <p className="text-xs font-semibold text-dhs-800 uppercase tracking-wide mb-2 border-b border-slate-200 pb-1">Billing</p>
      <table className="w-full text-sm">
        <tbody>
          {sale.billingItems.map((it: any) => (
            <tr key={it.id} className="border-b border-slate-100">
              <td className="py-1.5">{it.description}</td>
              <td className="py-1.5 text-right">{money(it.amount)}</td>
            </tr>
          ))}
          <tr>
            <td className="pt-2 font-medium">Total</td>
            <td className="pt-2 font-semibold text-right">{money(total)}</td>
          </tr>
        </tbody>
      </table>

      {sale.payment && (
        <div className="mt-3">
          <p className="text-sm text-slate-600">
            {sale.payment.method === "CASH"
              ? `Paid in cash${sale.payment.paidAt ? ` on ${new Date(sale.payment.paidAt).toLocaleString()}` : ""}`
              : `Insurance (${sale.payment.insuranceProvider || "—"}) — claim #${sale.payment.claimNo || "—"} — status: ${sale.payment.claimStatus}`}
          </p>
          {sale.payment.method === "INSURANCE" && (sale.payment.installments || []).length > 0 && (
            <div className="mt-2">
              <p className="text-xs font-medium text-slate-500 mb-1">Payments received</p>
              <table className="w-full text-xs">
                <tbody>
                  {sale.payment.installments.map((inst: any) => (
                    <tr key={inst.id} className="border-b border-slate-100">
                      <td className="py-1 text-slate-500">{new Date(inst.recordedAt).toLocaleString()}</td>
                      <td className="py-1 text-right">{money(inst.amount)}</td>
                    </tr>
                  ))}
                  <tr>
                    <td className="pt-1 font-medium">Total received</td>
                    <td className="pt-1 font-semibold text-right">{money(sale.payment.amountPaid)}</td>
                  </tr>
                  {Number(sale.payment.amountPaid) < total && (
                    <tr>
                      <td className="text-amber-700 font-medium">Remaining balance</td>
                      <td className="text-amber-700 font-semibold text-right">{money(total - Number(sale.payment.amountPaid))}</td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}

      <div className="mt-10 pt-4 border-t border-slate-200 text-xs text-slate-400">
        This receipt was generated by Digital Health Solutions and reflects records as of the generation time above.
      </div>
    </PrintShell>
  );
}
